title       = "ytmusic"
baseURL     = "https://ytmusic-cli.tamnd.com/"
description = "A command line for ytmusic."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/ytmusic-cli"
